import KidsLike from 'shared/assets/image-project/Screenshot 2023-01-10 at 17.16.55.png';
import img1 from 'shared/assets/image-project/Screenshot 2023-01-10 at 17.13.35.png';
import img2 from 'shared/assets/image-project/viterstudio.jpeg';
import img11 from 'shared/assets/image-project/vitercourse.png';
import img12 from 'shared/assets/image-project/dr-rusakova.png';
import img14 from 'shared/assets/image-project/dental.png';
import img15 from 'shared/assets/image-project/7red.jpeg';
import img16 from 'shared/assets/image-project/hhdc.png';
import img17 from 'shared/assets/image-project/keratin.png';
import img18 from 'shared/assets/image-project/taft.jpeg';
import img3 from 'shared/assets/image-project/Screenshot 2023-01-10 at 17.15.57.png';
import img4 from 'shared/assets/image-project/Screenshot 2023-01-10 at 17.18.03.png';
import img5 from 'shared/assets/image-project/Screenshot 2023-01-10 at 17.19.02.png';
import img6 from 'shared/assets/image-project/Screenshot 2023-01-10 at 17.19.53.png';
import img7 from 'shared/assets/image-project/Screenshot 2023-01-10 at 17.20.42.png';
import img8 from 'shared/assets/image-project/Screenshot 2023-01-10 at 17.21.47.png';
import img9 from 'shared/assets/image-project/Screenshot 2023-01-10 at 18.02.46.png';
import img10 from 'shared/assets/image-project/Screenshot 2023-01-10 at 18.07.57.png';

export const portfolioList = [
  {
    id: 12,
    title: 'Viter Store',
    skills: ['React', 'Sass', 'i18next'],
    role: 'Developer',
    text: '',
    link: 'https://viter-hairstore.com/',
    source_link: '',
    img_bg: `${img11}`,
    img_medium: '',
    img_small: '',
  },
  {
    id: 13,
    title: 'Dr Rusakova',
    skills: ['React', 'Sass', 'i18next'],
    role: 'Developer',
    text: '',
    link: 'https://viter-hairstore.com/',
    source_link: '',
    img_bg: `${img12}`,
    img_medium: '',
    img_small: '',
  },
  {
    id: 14,
    title: 'Innovation Dental Clinic',
    skills: ['React', 'Sass', 'i18next'],
    role: 'Developer',
    text: '',
    link: 'https://innovationdentalclinic.pl/',
    source_link: '',
    img_bg: `${img14}`,
    img_medium: '',
    img_small: '',
  },
  {
    id: 15,
    title: 'Wedding 7Red',
    skills: ['React', 'Sass'],
    role: 'Developer',
    text: '',
    link: 'https://wedding.7redfilm.com.ua/',
    source_link: '',
    img_bg: `${img15}`,
    img_medium: '',
    img_small: '',
  },
  {
    id: 16,
    title: 'HHDC / Amsterdam',
    skills: ['React', 'Sass'],
    role: 'Developer',
    text: '',
    link: 'https://highheelsdancecamp.com/',
    source_link: '',
    img_bg: `${img16}`,
    img_medium: '',
    img_small: '',
  },
  {
    id: 17,
    title: 'Keratin Prof store',
    skills: ['OpenCart', 'PHP'],
    role: 'Developer',
    text: 'Online store for cosmetics',
    link: 'https://keratinprof.pl/',
    source_link: '',
    img_bg: `${img17}`,
    img_medium: '',
    img_small: '',
  },
  {
    id: 18,
    title: 'Taft store',
    skills: ['PHP', 'Java script', 'Sass', 'HTML5', 'Bootstrap'],
    role: 'Developer',
    text: 'Online store for cosmetics',
    link: 'https://www.taft.nl/',
    source_link: '',
    img_bg: `${img18}`,
    img_medium: '',
    img_small: '',
  },
  {
    id: 2,
    title: 'Viter studio',
    skills: ['HTML5', 'Sass', 'Java Script', 'Parcel', 'JQuery'],
    role: 'Developer',
    text: '',
    link: 'https://viter-hairstudio.com.ua/',
    source_link: '',
    img_bg: `${img2}`,
    img_medium: '',
    img_small: '',
  },
  {
    id: 3,
    title: 'Kameleon',
    role: 'Developer',
    skills: ['HTML5', 'Bootstrap', 'Sass', 'JavaScript', 'JQuery'],
    text: 'It"s was test task for company',
    link: 'https://myrhoiazov.github.io/bootstrap-app/',
    source_link: '',
    img_bg: `${img1}`,
    img_medium: '',
    img_small: '',
  },
  {
    id: 4,
    title: 'WevStudio',
    role: 'Developer',
    skills: ['HTML5', 'Sass', 'JavaScript'],
    text: '',
    link: 'https://myrhoiazov.github.io/goit-markup-hw-08/',
    source_link: '',
    img_bg: `${img3}`,
    img_medium: '',
    img_small: '',
  },
  {
    id: 1,
    title: 'Kids Like application',
    skills: ['Sass', 'React', 'Redux', 'REST API', 'Parcel', 'User Auth'],
    role: 'Developer',
    text: '',
    link: 'https://kidslikes.netlify.app/auth',
    source_link: '',
    img_bg: `${KidsLike}`,
    img_medium: '',
    img_small: '',
  },
  {
    id: 5,
    title: 'Book Contact',
    skills: ['Sass', 'React', 'Redux', 'REST API', 'REST API', 'User Auth'],
    role: 'Developer',
    text: '',
    link: 'https://myrhoiazov.github.io/goit-react-hw-08-phonebook/',
    source_link: '',
    img_bg: `${img4}`,
    img_medium: '',
    img_small: '',
  },
  {
    id: 6,
    title: 'Trend Film',
    skills: ['Sass', 'React', 'Redux', 'REST API'],
    role: 'Developer',
    text: '',
    link: 'https://myrhoiazov.github.io/goit-react-hw-05-movies/',
    source_link: '',
    img_bg: `${img5}`,
    img_medium: '',
    img_small: '',
  },
  {
    id: 7,
    title: 'Filmoteka',
    skills: ['HTML5', 'Sass', 'Java Script', 'Parcel', 'REST API'],
    role: 'Scrum master',
    text: '',
    link: 'https://myrhoiazov.github.io/js-team-project/',
    source_link: '',
    img_bg: `${img6}`,
    img_medium: '',
    img_small: '',
  },
  {
    id: 8,
    title: 'IceCream',
    skills: ['HTML5', 'Sass', 'Java Script', 'Parcel'],
    role: 'Developer',
    text: '',
    link: 'https://myrhoiazov.github.io/go-it-project-html-css/',
    source_link: '',
    img_bg: `${img7}`,
    img_medium: '',
    img_small: '',
  },
  {
    id: 9,
    title: 'CodeX',
    skills: ['HTML5', 'Sass'],
    role: 'Developer',
    text: '',
    link: 'https://myrhoiazov.github.io/codX-test/',
    source_link: '',
    img_bg: `${img8}`,
    img_medium: '',
    img_small: '',
  },
  {
    id: 10,
    title: 'Karnaval Fest',
    skills: ['Wordpress'],
    role: 'Developer',
    text: '',
    link: 'https://karnavalfest.com/',
    source_link: '',
    img_bg: `${img9}`,
    img_medium: '',
    img_small: '',
  },
  {
    id: 11,
    title: 'Dance Studio',
    skills: ['Wordpress'],
    role: 'Developer',
    text: '',
    link: 'https://dandancecomplex.com/',
    source_link: '',
    img_bg: `${img10}`,
    img_medium: '',
    img_small: '',
  },
];
